name: CI
on:
  push:
    branches: [main]
jobs:
  format-lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" bun --bunx prisma generate
      - run: bun run format-lint:check
      - run: bun run typecheck